
development: &dev 
  host: 127.0.0.1
  adapter: postgresql
  pool: 5  
  enconding: unicode 
  database: aplicativo_dev
  username: postgres
  password: postgres

stanging:
  <<: *dev  

production:
  <<: *dev
